"""baseline: scribble schema as create_all built it (int PKs)

Revision ID: e17599b0880a
Revises: 
Create Date: 2026-08-16 14:13:29.258319

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import scribble.db  # noqa: F401  -- revisions reference scribble.db.SoftHostId by name

revision: str = 'e17599b0880a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scribble_assessment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('default_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('scribble_checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('coverage', 'reminder', 'compliance', name='checklistkind'), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('customized', sa.Boolean(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('scribble_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scribble_engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', scribble.db.SoftHostId(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_type', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('guid', sa.String(length=64), nullable=True),
    sa.Column('distribution_list', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('owner_id', scribble.db.SoftHostId(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index(op.f('ix_scribble_engagements_owner_id'), 'scribble_engagements', ['owner_id'], unique=False)
    op.create_table('scribble_enrichment_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('current_severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('suggested_severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('reason', sa.String(length=280), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scribble_enrichment_proposals_engagement_id'), 'scribble_enrichment_proposals', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_scribble_enrichment_proposals_finding_id'), 'scribble_enrichment_proposals', ['finding_id'], unique=False)
    op.create_index(op.f('ix_scribble_enrichment_proposals_status'), 'scribble_enrichment_proposals', ['status'], unique=False)
    op.create_table('scribble_report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('engagement_type', sa.String(length=64), nullable=True),
    sa.Column('docx_path', sa.String(length=1024), nullable=True),
    sa.Column('html_template_name', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scribble_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scribble_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('engagement', 'finding', name='variablescope'), nullable=False),
    sa.Column('value_type', sa.Enum('str_', 'bool_', 'list_', 'html', name='variabletype'), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('from_facts', sa.JSON(), nullable=True),
    sa.Column('target_column', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('scribble_vuln_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('default_severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=255), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('content_html', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('machine_authored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scribble_checklist_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('framework', sa.String(length=128), nullable=True),
    sa.Column('control_ref', sa.String(length=128), nullable=True),
    sa.Column('default_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['scribble_checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scribble_engagement_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('coverage', 'reminder', 'compliance', name='checklistkind'), nullable=False),
    sa.Column('include_in_report', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['scribble_engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scribble_finding_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('order_mode', sa.Enum('auto_severity', 'manual', name='ordermode'), nullable=False),
    sa.Column('include_in_report', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['scribble_assessment_types.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['scribble_engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scribble_report_renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('html', 'docx', name='reportformat'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['scribble_engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scribble_template_tags',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['scribble_tags.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['scribble_vuln_templates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'tag_id')
    )
    op.create_table('scribble_vuln_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('title_pattern', sa.String(length=255), nullable=True),
    sa.Column('dedupe_prefix', sa.String(length=255), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['scribble_vuln_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scribble_vuln_map_dedupe_prefix'), 'scribble_vuln_map', ['dedupe_prefix'], unique=False)
    op.create_index(op.f('ix_scribble_vuln_map_source'), 'scribble_vuln_map', ['source'], unique=False)
    op.create_table('scribble_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('source_finding_id', scribble.db.SoftHostId(length=64), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='confidence'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('new', 'triaged', 'accepted_risk', 'false_positive', 'fixed', 'needs_retest', name='findingstatus'), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('content_html', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('include_in_report', sa.Boolean(), nullable=False),
    sa.Column('target_host', sa.String(length=255), nullable=True),
    sa.Column('target_port', sa.String(length=16), nullable=True),
    sa.Column('target_url', sa.String(length=1024), nullable=True),
    sa.Column('asset_id', scribble.db.SoftHostId(length=64), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['scribble_engagements.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['scribble_finding_groups.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['scribble_findings.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['scribble_vuln_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scribble_findings_source_finding_id'), 'scribble_findings', ['source_finding_id'], unique=False)
    op.create_table('scribble_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('screenshot', 'text', 'file', 'inline_image', name='artifactkind'), nullable=False),
    sa.Column('placement', sa.Enum('attached', 'inline', name='artifactplacement'), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('include_in_report', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['scribble_engagements.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['scribble_findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scribble_artifacts_idempotency_key'), 'scribble_artifacts', ['idempotency_key'], unique=False)
    op.create_table('scribble_collab_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=64), nullable=False),
    sa.Column('ydoc_state', sa.LargeBinary(), nullable=True),
    sa.Column('updated_at_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['scribble_findings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'block')
    )
    op.create_table('scribble_engagement_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_checklist_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('framework', sa.String(length=128), nullable=True),
    sa.Column('control_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_checklist_id'], ['scribble_engagement_checklists.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['scribble_findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scribble_finding_tags',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['scribble_findings.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['scribble_tags.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'tag_id')
    )
    op.create_table('scribble_variable_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['scribble_engagements.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['scribble_findings.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['scribble_variables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_id', 'engagement_id', 'finding_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scribble_variable_values')
    op.drop_table('scribble_finding_tags')
    op.drop_table('scribble_engagement_checklist_items')
    op.drop_table('scribble_collab_docs')
    op.drop_index(op.f('ix_scribble_artifacts_idempotency_key'), table_name='scribble_artifacts')
    op.drop_table('scribble_artifacts')
    op.drop_index(op.f('ix_scribble_findings_source_finding_id'), table_name='scribble_findings')
    op.drop_table('scribble_findings')
    op.drop_index(op.f('ix_scribble_vuln_map_source'), table_name='scribble_vuln_map')
    op.drop_index(op.f('ix_scribble_vuln_map_dedupe_prefix'), table_name='scribble_vuln_map')
    op.drop_table('scribble_vuln_map')
    op.drop_table('scribble_template_tags')
    op.drop_table('scribble_report_renders')
    op.drop_table('scribble_finding_groups')
    op.drop_table('scribble_engagement_checklists')
    op.drop_table('scribble_checklist_template_items')
    op.drop_table('scribble_vuln_templates')
    op.drop_table('scribble_variables')
    op.drop_table('scribble_tags')
    op.drop_table('scribble_report_templates')
    op.drop_index(op.f('ix_scribble_enrichment_proposals_status'), table_name='scribble_enrichment_proposals')
    op.drop_index(op.f('ix_scribble_enrichment_proposals_finding_id'), table_name='scribble_enrichment_proposals')
    op.drop_index(op.f('ix_scribble_enrichment_proposals_engagement_id'), table_name='scribble_enrichment_proposals')
    op.drop_table('scribble_enrichment_proposals')
    op.drop_index(op.f('ix_scribble_engagements_owner_id'), table_name='scribble_engagements')
    op.drop_table('scribble_engagements')
    op.drop_table('scribble_clients')
    op.drop_table('scribble_checklist_templates')
    op.drop_table('scribble_assessment_types')
    # ### end Alembic commands ###
